pip install behave
pip install redis
pip install pyserial
pip install tqdm
pip install ipdb
pip install appium-python-client
pip install requests
pip install selenium
pip install nmap
pip install pillow
pip install pytesseract
pip install numpy
pip install remi
pip install pexpect
pip install pxssh